/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import bl.Carrera;
import bl.Fachada;
import bl.Jornada;
import java.util.Calendar;
import java.util.Date;



/**
 *
 * @author Fossemale
 */
public class DlgCrearCarrera extends javax.swing.JDialog {

    /**
     * Creates new form DlgCrearCarrera
     */
    Fachada fac = Fachada.getInstancia();
    DlgSeleccionarCaballosCarrera dialogCaballos;
    java.awt.Frame jFrame;
    public DlgCrearCarrera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jFrame = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnCrearCarrera = new javax.swing.JButton();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        lblMensaje = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Crear Carrera");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 21, 124, 14);

        jLabel2.setText("Fecha :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(101, 56, 69, 14);

        jLabel3.setText("Nombre :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(103, 97, 77, 14);

        txtDay.setText("6");
        getContentPane().add(txtDay);
        txtDay.setBounds(208, 53, 26, 20);

        txtNombre.setText("AAAA");
        getContentPane().add(txtNombre);
        txtNombre.setBounds(208, 94, 143, 20);

        btnCrearCarrera.setText("Continuar");
        btnCrearCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCarreraActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearCarrera);
        btnCrearCarrera.setBounds(219, 140, 101, 42);

        txtMonth.setText("6");
        getContentPane().add(txtMonth);
        txtMonth.setBounds(240, 53, 25, 20);

        txtYear.setText("2014");
        getContentPane().add(txtYear);
        txtYear.setBounds(271, 53, 80, 20);
        getContentPane().add(lblMensaje);
        lblMensaje.setBounds(107, 200, 360, 23);

        jLabel4.setText("dd/mm/yyyy");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(361, 56, 83, 14);

        setBounds(0, 0, 556, 312);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCarreraActionPerformed
        // TODO add your handling code here:
       Date fch;
       int year;
       int month;
       int day;
       Calendar cal = Calendar.getInstance();
        try {
            year = Integer.parseInt(txtYear.getText());
            month =Integer.parseInt(txtMonth.getText());
            day = Integer.parseInt(txtDay.getText());                                   
            cal.clear();
            cal.set(Calendar.YEAR, year);
            cal.set(Calendar.MONTH, month);
            cal.set(Calendar.DATE, day);
            fch= cal.getTime();
            
        } catch (Exception e) {
            fch = new Date();          
            cal.setTime(fch);
            cal.set(Calendar.YEAR, cal.get(Calendar.YEAR));
            cal.set(Calendar.MONTH, cal.get(Calendar.MONTH));
            cal.set(Calendar.DATE,cal.get(Calendar.DAY_OF_MONTH));
            fch = cal.getTime();   
        }
                
        String nombre = txtNombre.getText();        
        Carrera c = new Carrera(nombre, fch);
        
        if(fac.getHipodromoActual().validarDatosCarrera(c)){
            if ( c.validarFecha(fch)) {
                fac.getHipodromoActual().agregarCarrera(c);
                dialogCaballos = new DlgSeleccionarCaballosCarrera(jFrame, true, c);
                dialogCaballos.setVisible(true);

            } else { 
                lblMensaje.setText("La fecha de la carrera no es correcta");
            }
        } else {
            lblMensaje.setText("El nombre para de carrera para la jornada ya existe");
        }
        
        
        
    }//GEN-LAST:event_btnCrearCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCrearCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCrearCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCrearCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCrearCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCrearCarrera dialog = new DlgCrearCarrera(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
