/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import bl.Administrador;
import bl.Fachada;
import bl.Hipodromo;
import java.util.ArrayList;
import util.Observable;
import util.Observador;

/**
 *
 * @author Fossemale
 */
public class DlgSeleccionarHipodromo extends javax.swing.JDialog  implements Observador{

    /**
     * Creates new form DlgSeleccionarHipodromo
     */
    Fachada fac = Fachada.getInstancia();
    public DlgSeleccionarHipodromo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fac.agregarObservador(this);
        seleccionarHipodromo();
             
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbHipodromos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnSeeccionarHipodromo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Seleccionar Hipodromo");

        btnSeeccionarHipodromo.setText("Seleccionar");
        btnSeeccionarHipodromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeccionarHipodromoActionPerformed(evt);
            }
        });

        jLabel2.setText("Bienvenido :");

        lblBienvenida.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(cmbHipodromos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnSeeccionarHipodromo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBienvenida))
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbHipodromos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeeccionarHipodromo))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeeccionarHipodromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeccionarHipodromoActionPerformed
        // TODO add your handling code here:        
        Hipodromo h = (Hipodromo) cmbHipodromos.getItemAt(cmbHipodromos.getSelectedIndex());
        fac.seleccionarHipodromo(h);
        System.out.println(fac.getHipodromoActual());
        this.setVisible(false);
        
    }//GEN-LAST:event_btnSeeccionarHipodromoActionPerformed

    private void seleccionarHipodromo() {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        ArrayList<Hipodromo> hipodromos = fac.getHipodromos();
            for (Hipodromo h : hipodromos) {
                cmbHipodromos.addItem(h);
            }
            cmbHipodromos.getItemAt(1);
    }

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeeccionarHipodromo;
    private javax.swing.JComboBox cmbHipodromos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(Observable origen, Object param) {
        if(Fachada.Evento.agregarHipodromo.equals(param)){
            cmbHipodromos.removeAllItems();
            seleccionarHipodromo();
        }
    }
    
}
